#!/bin/sh
set -eu
. "$(dirname $(readlink -f "$0"))/.env"

if pid=$("${base_dir}/is-up"); then
  log "${app_name} is already running with pid ${pid}."
else
  PATH="${base_dir}/quirk:$PATH" python3 -m "${package_name}" --hidraw --udp ${host:+--udp-host "${host}"} ${port:+--udp-port "${port}"} >"${log_file}" 2>&1 &
fi
