#!/bin/sh
source="$(find /usr/lib/python*.*/site-packages/dsdrv/backends -name hidraw.py)"
cp -a "${source}" "${source}.backup-ds5"
patch "${source}" << 'EOF'
+++ ${source}
--- hidraw.py
@@ -123,8 +123,10 @@

 HID_DEVICES = {
     "Sony Interactive Entertainment Wireless Controller": HidrawUSBDSDevice,
+    "Sony Interactive Entertainment DualSense Wireless Controller": HidrawUSBDSDevice,
     "Sony Computer Entertainment Wireless Controller": HidrawUSBDSDevice,
     "Wireless Controller": HidrawBluetoothDSDevice,
+    "DualSense Wireless Controller": HidrawBluetoothDSDevice,
 }

EOF
echo >&2 "dsdrv-cemuhook was patched for PS5 controllers."
