= batocera-extra
:url-batocera: https://github.com/batocera-linux/batocera.linux/
Extended motion and touch control for batocera
:toc: preamble
:toclevels: 4

This project is a proof of concept to play games with motion and touch control in the retro gaming distribution {url-batocera}[batocera].

## Project status

This project should be considered experimental. It demonstrates how motion and touch control can be added to batocera.
Currently, some ugly hacks are required to achieve this. Installation requires command line access to batocera through a SSH shell. Main goal of this project is to properly integrate the features into the core of batocera in the future.

The project is tested against the x86_64 platform. There are no hard dependencies on this architecture, so it may well
run on other architectures, too, but this is currently untested.

## Installation

. Open a shell on the batocera host
.. either via SSH
.. or by pressing F1 in the main menu to open the file manager and then F4 to open a terminal
. Copy this directory to `/userdata/extra` to your batocera host:
+
[source,console]
----
$ mkdir -p /userdata/extra && wget -O - https://github.com/git-developer/batocera-extra/tarball/main | gunzip | tar x --strip-components 1 -C /userdata/extra
----
. Follow the installation instructions of the features you're interested in. Each feature has its own subdirectory containing a README file.
. Modify your `/userdata/system/custom.sh` according to your needs.
.. See `bin/custom.sh` for an example.
.. If you don't have a `custom.sh` yet, you can simply create a link to the example:
+
[source,console]
----
$ ln -s /userdata/extra/bin/custom.sh /userdata/system/custom.sh
----

## Content
### Features
#### Server for motion control using a controller with modern Linux drivers (e.g. Nintendo Switch, Sony DS4 & DS5)

* See link:evdevhook2/README.adoc[evdevhook2].

#### Server for motion control using a Nintendo Switch controller

* See link:joycond-cemuhook/README.adoc[joycond-cemuhook].

#### Server for motion and touch control using a Sony DS4 or DS5 controller (PS4 Dual Shock / PS5 Dual Sense)

* See link:dsdrv-cemuhook/README.adoc[dsdrv-cemuhook].

#### Server for motion control using a Nintendo Wiimote

* See link:linuxmotehook2/README.adoc[linuxmotehook2].

#### Server for motion control using a Steam Deck

* See link:sdgyrodsu/README.adoc[sdgyrodsu].

#### Server for motion and touch control using a Steam Controller

* See link:sc-controller/README.adoc[sc-controller].

#### Server for motion and touch control using a smartphone

* For touch, see link:remote-touchpad/README.adoc[remote-touchpad].
* For motion, see _Android MotionSource server_ in the https://cemuhook.sshnuke.net/padudpserver.html[cemuhook documentation]
* For game controller emulation, see https://github.com/breeze2/dsu-controller-guides[DSUController Guides]

### Patches
Patches are located in the `patches/` directory.

#### `patch-cemu-generator-for-cemuhook`

* A patch for the configuration generator of Cemu. It adds support for motion configuration in Cemu.

### Scripts
Scripts are located in the `bin/` directory.

#### `custom.sh`
* An example for `/userdata/system/custom.sh` that enables most features of this project.

#### `on-game-condition`
* A template for files in the `/userdata/system/scripts` directory.

#### `read-temperatures`
* A script to read system temperatures.

#### `squash-mount`
* A script to simplify (un)mounting squashfs roms for one or all systems to subdirectories of `/var/run/squashfs`.

#### `system-summary`
* A script to create a system summary (cpu, memory). May be bound to a key or controller button, e.g.:
+
./userdata/system/configs/multimedia_keys.conf
[source.conf]
----
KEY_F12 1 /userdata/extra/bin/system-summary | sed 's/°/ /' | HOME=/userdata/system XAUTHORITY=/var/lib/.Xauthority DISPLAY=:0.0 osd_cat -f -*-*-bold-*-*-*-38-120-*-*-*-*-*-* -cred -s 3 -d 4
----

## Emulator configuration for motion and touch control
This section explains the emulator configuration that is required to play games with motion and touch control. This configuration has to be performed once only, it will be persisted across boots.

The configuration generator for Cemu in current batocera doesn't offer support for motion and touch control. Actually, it even prevents it because it overrides custom changes in the affected configuration files. To avoid this, the <<Patches>> are required.

Once the configuration is applied, the emulators will behave as follows:

* Touch input is read from the emulator window. This enables the following sources for touch input:
** The touchpad of a DS4 or DS5 controller
** A smartphone connected via remote touchpad
** A mouse connected to the batocera host

* Motion input is read from a cemuhook server.
** For a controller connected to evdevhook2, use `localhost` and `26766`.
** For a Nintendo controller connected to joycond-cemuhook, use `localhost` and `26761`.
** For a DS4 or DS5 controller connected to dsdrv-cemuhook, use `localhost` and `26762`.
** For a Wiimote connected to linuxmotehook2, use `localhost` and the port from your linuxmotehook2 configuration file.
** For a Steam Deck connected to sdgyrodsu, use `localhost` and `26767`.
** For a Steam Controller connected to sc-controller, use `localhost` and `26768`.
** For a smartphone, use the hostname/ip of the smartphone and the port configured in the app of your choice (e.g. _MotionSource_ or _DSUController_).

### Citra
./userdata/system/configs/citra-emu/qt-config.ini
----
[Controls]
profiles\1\touch_device=engine:emu_window
profiles\1\touch_device\default=true
profiles\1\motion_device=engine:cemuhookudp
profiles\1\motion_device\default=false
profiles\1\udp_input_address=localhost
profiles\1\udp_input_address\default=false
profiles\1\udp_input_port=26766
profiles\1\udp_input_port\default=false
----

Notes:

* The settings may be set by either editing the configuration file using a text editor or using the UI: File Manager -> Applications -> citra-emu-config -> Menu _Emulation_ -> Entry _Configure_ -> List Entry _Controls_ -> Tab _Input_ -> Button _Motion / Touch Control..._

### Cemu
./userdata/system/batocera.conf
----
wiiu.cemuhook_server_ip=localhost
wiiu.cemuhook_server_port=26766
----

Notes:

* The settings must be set by editing the configuration file using a text editor.
* Without patching the Cemu configuration generator, these settings have no effect.
* Implementation details:
** Without patch, the generator uses the SDL controller API without (working) motion support.
** The patch reads the settings from `batocera.conf` and adds them to the controller configuration files in `/userdata/system/configs/cemu/controllerProfiles/controller*.xml`.
