= batocera-extra
:url-batocera: https://github.com/batocera-linux/batocera.linux/
Extended motion and touch control for batocera
:toc: preamble
:toclevels: 4

This project is a proof of concept to play games with motion and touch control in the retro gaming distribution {url-batocera}[batocera].

## Project status

This project should be considered experimental. It demonstrates how motion and touch control can be added to batocera.
Installation requires command line access to batocera through a SSH shell.
Main goal of this project is to properly integrate the features into the core of batocera in the future.

The project is tested against the x86_64 platform. There are no hard dependencies on this architecture,
so it may well run on other architectures, too, but this is currently untested.

## Installation

. Open a shell on the batocera host
.. either via SSH
.. or by pressing F1 in the main menu to open the file manager and then F4 to open a terminal
. Copy this directory to `/userdata/extra` to your batocera host:
+
[source,console]
----
$ mkdir -p /userdata/extra && wget -O - https://github.com/git-developer/batocera-extra/tarball/main | gunzip | tar x --strip-components 1 -C /userdata/extra
----
. Register the features as batocera service.
.. By default, all features are registered. To exclude a feature, run `/userdata/extra/<feature>/service hide`.
.. Run
+
[source,console]
----
/userdata/extra/bin/extra-services register
batocera-services enable extra_patches
batocera-services start extra_patches
----
. Follow the installation instructions of the features you're interested in.
.. For the basics, see section <<Emulator configuration for motion and touch control>>
.. Each feature has its own subdirectory containing a README file.

## Content
### Features
#### Server for motion control using a controller with modern Linux drivers (e.g. Nintendo Switch, Sony DS4 & DS5)

* See link:motion_evdev/README.adoc[motion_evdev].

#### Server for motion control using a Nintendo Switch controller

* See link:motion_nintendo/README.adoc[motion_nintendo].

#### Server for motion and touch control using a Sony DS4 or DS5 controller (PS4 Dual Shock / PS5 Dual Sense)

* See link:motion_sony/README.adoc[motion_sony].

#### Server for motion control using a Nintendo Wiimote

* See link:motion_wiimote/README.adoc[motion_wiimote].

#### Server for motion control using a Steam Deck

* See link:motion_steam_deck/README.adoc[motion_steam_deck].

#### Server for motion and touch control using a Steam Controller

* See link:motion_steam_controller/README.adoc[motion_steam_controller].

#### Server for motion and touch control using a smartphone

* For touch, see link:remote-touchpad/README.adoc[remote-touchpad].
* For motion, see _Android MotionSource server_ in the https://cemuhook.sshnuke.net/padudpserver.html[cemuhook documentation]
* For game controller emulation, see https://github.com/breeze2/dsu-controller-guides[DSUController Guides]

### Scripts
Scripts are located in the `bin/` directory.

#### `extra-services`
* Script to manage the features of this project.
  This script is required only once to register the features as batocera services.
  It may be useful when something goes wrong.

#### `on-game-condition`
* A template for files in the `/userdata/system/scripts` directory.

#### `read-temperatures`
* A script to read system temperatures.

#### `squash-mount`
* A script to simplify (un)mounting squashfs roms for one or all systems to subdirectories of `/var/run/squashfs`.

#### `system-summary`
* A script to create a system summary (cpu, memory). May be bound to a key or controller button, e.g.:
+
./userdata/system/configs/multimedia_keys.conf
[source.conf]
----
KEY_F12 1 /userdata/extra/bin/system-summary | sed 's/°/ /' | HOME=/userdata/system XAUTHORITY=/var/lib/.Xauthority DISPLAY=:0.0 osd_cat -f -*-*-bold-*-*-*-38-120-*-*-*-*-*-* -cred -s 3 -d 4
----

## Emulator configuration for motion and touch control
This section explains the emulator configuration that is required to play games with motion and touch control.
The configuration has to be performed once only, it will be persisted across boots and batocera updates.

The configuration is applied by activating a motion service (Main Menu / System Settings / Services).
Each time a service is activated, the batocera configuration is updated so that Cemu and Citra will behave as follows:

* Motion input is read from the cemuhook server of the activated service.
* Touch input is read from the emulator window. This enables the following sources for touch input:
** The touchpad of a DS4 or DS5 controller
** A smartphone connected via remote touchpad
** A mouse connected to the batocera host

To use a smartphone as motion provider, you have to set the hostname/ip of the smartphone and the port
configured in the app of your choice (e.g. _MotionSource_ or _DSUController_).
This must be done manually by editing the batocera configuration file `/userdata/system/batocera.conf`.

[NOTE]
====
Make sure that _extra_patches_ is enabled as batocera service.
The configuration generators for Cemu and Citra in current batocera don't offer support for motion and touch control.
Thus, the included patches are required to be started as batocera service.
====

## Implementation details

Whenever one of the motion services is started, the following settings are written to the batocera configuration file:

./userdata/system/batocera.conf
----
3ds.citra_motion_device=engine:cemuhookudp
3ds.citra_touch_device=engine:emu_window
3ds.citra_udp_input_address=localhost
3ds.citra_udp_input_port=<service port>

wiiu.cemu_touchpad=1
wiiu.cemuhook_server_ip=localhost
wiiu.cemuhook_server_port=<service port>
----

The port is read from the activated service:
* For a controller connected to motion_evdev: `26766`
* For a Nintendo controller connected to motion_nintendo: `26761`
* For a DS4 or DS5 controller connected to motion_sony: `26762`
* For a Wiimote connected to motion_wiimote: the port from your linuxmotehook2 configuration file.
* For a Steam Deck connected to motion_steam_deck: `26767`.
* For a Steam Controller connected to motion_steam_controller: `26760`.
