= batocera-extra
:url-batocera: https://github.com/batocera-linux/batocera.linux/
Extended motion and touch control for batocera
:toc: preamble
:toclevels: 4

This project is a proof of concept to play games with motion and touch control in the retro gaming distribution {url-batocera}[batocera].

## Project status

This project should be considered experimental. It demonstrates how motion and touch control can be added to batocera.
Currently, some ugly hacks are required to achieve this. Installation requires command line access to batocera through a SSH shell. Main goal of this project is to properly integrate the features into the core of batocera in the
future.

The project is tested against the x86_64 platform. There are no hard dependencies on this architecture, so it may well
run on other architectures, too, but this is currently untested.

## Installation

. Open a shell on the batocera host
.. either via SSH
.. or by pressing F1 in the main menu to open the file manager and then F4 to open a terminal
. Copy this directory to `/userdata/extra` to your batocera host:
+
[source,console]
----
$ mkdir -p /userdata/extra && wget -O - https://github.com/git-developer/batocera-extra/tarball/main | gunzip | tar x --strip-components 1 -C /userdata/extra
----
. Follow the installation instructions of the features you're interested in. Each feature has its own subdirectory containing a README file.
. Modify your `/userdata/system/custom.sh` according to your needs.
.. See `bin/custom.sh` for an example.
.. If you don't have a `custom.sh` yet, you can simply create a link to the example:
+
[source,console]
----
$ ln -s /userdata/extra/bin/custom.sh /userdata/system/custom.sh
----

## Content
### Features
#### Motion control using a Nintendo Switch controller

* See link:joycond-cemuhook/README.adoc[joycond-cemuhook].

#### Motion and touch control using a Sony DS4 controller (PS4 Dual Shock)

* See link:ds4drv-cemuhook/README.adoc[ds4drv-cemuhook].

#### Motion and touch control using a smartphone

* For touch, see link:remote-touchpad/README.adoc[remote-touchpad].
* For motion, see _Android MotionSource server_ in the https://cemuhook.sshnuke.net/padudpserver.html[cemuhook documentation]

### Patches
Patches are located in the `patches/` directory.

#### `patch-citra-generator-for-cemuhook`

* A patch for the configuration generator of Citra. It adds support for motion and touch configuration in Citra.
* Related pull request: https://github.com/batocera-linux/batocera.linux/pull/8080[#8080]

#### `patch-cemu-generator-for-cemuhook`

* A patch for the configuration generator of Cemu. It adds generation of the cemuhook configuration file `cemuhook.ini` allowing configuration of motion control.
* Written for batocera v35 which contains the Windows build of cemu. This patch will probably not work in batocera v36 and above, because v36 introduces the linux version of cemu.

#### `patch-citra-generator-for-language`

* A patch for the configuration generator of Citra. It fixes broken language detection.
* Related pull request: https://github.com/batocera-linux/batocera.linux/pull/8073[#8073]
* May be applied to batocera v35, will be available in v36.

#### `patch-cemu-generator-for-squashfs`

* A patch for the configuration generator of Cemu. It adds support for arbitrary location of `.rpx` files within Loadiine roms.
* Related pull requests: https://github.com/batocera-linux/batocera.linux/pull/8052[#8052] & https://github.com/batocera-linux/batocera.linux/pull/8053[#8053]
* May be applied to batocera v35, will be available in v36.

#### `patch-batocera-info-for-pro-controller`
* A script that patches `batocera-info` for Switch Pro Controllers.
* For Nintendo controllers, the kernel module https://github.com/emilyst/hid-nx-dkms[hid-nx] is used which provides the battery status as https://github.com/emilyst/hid-nx-dkms/blob/974d6c407296c47390d99f008933846c86f52bb9/hid-nx.c#L1533[level enum] (e.g. `low` and `high`) instead of a percentage.
* This patch has only an effect on the `batocera-info` script and not on the battery level shown in the Emulation Station UI.

### Scripts
Scripts are located in the `bin/` directory.

#### `custom.sh`
* An example for `/userdata/system/custom.sh` that enables all features of this project.

#### `read-temperature`
* A script to read the CPU temperature from `hwmon` instead of `thermal_zone`. Useful for hosts where `/sys/devices/virtual/thermal` is not available. May be bound to a controller button, e.g.:
+
./userdata/system/configs/multimedia_keys.conf
[source.conf]
----
KEY_F12 1 /userdata/extra/bin/read-temperature | LANG=en_US HOME=/userdata/system XAUTHORITY=/var/lib/.Xauthority DISPLAY=:0.0 osd_cat -f -*-*-bold-*-*-*-38-120-*-*-*-*-*-* -cred -s 3 -d 4
----

#### `on-game-condition`
* A template for files in the `/userdata/system/scripts` directory.
