= batocera-extra
:url-batocera: https://github.com/batocera-linux/batocera.linux/
Extended motion and touch control for batocera
:toc: preamble
:toclevels: 4

This project is a proof of concept to play games with motion and touch control in the retro gaming distribution {url-batocera}[batocera].

## Project status

This project should be considered experimental. It demonstrates how motion and touch control can be added to batocera.
Currently, some ugly hacks are required to achieve this. Installation requires command line access to batocera through a SSH shell. Main goal of this project is to properly integrate the features into the core of batocera in the
future.

The project is tested against the x86_64 platform. There are no hard dependencies on this architecture, so it may well
run on other architectures, too, but this is currently untested.

## Installation

. Open a shell on the batocera host
.. either via SSH
.. or by pressing F1 in the main menu to open the file manager and then F4 to open a terminal
. Copy this directory to `/userdata/extra` to your batocera host:
+
[source,console]
----
$ mkdir -p /userdata/extra && wget -O - https://github.com/git-developer/batocera-extra/tarball/main | gunzip | tar x --strip-components 1 -C /userdata/extra
----
. Follow the installation instructions of the features you're interested in. Each feature has its own subdirectory containing a README file.
. Modify your `/userdata/system/custom.sh` according to your needs.
.. See `bin/custom.sh` for an example.
.. If you don't have a `custom.sh` yet, you can simply create a link to the example:
+
[source,console]
----
$ ln -s /userdata/extra/bin/custom.sh /userdata/system/custom.sh
----

## Content
### Features
#### Server for motion control using a Nintendo Switch controller

* See link:joycond-cemuhook/README.adoc[joycond-cemuhook].

#### Server for motion and touch control using a Sony DS4 controller (PS4 Dual Shock)

* See link:ds4drv-cemuhook/README.adoc[ds4drv-cemuhook].

#### Server for motion and touch control using a smartphone

* For touch, see link:remote-touchpad/README.adoc[remote-touchpad].
* For motion, see _Android MotionSource server_ in the https://cemuhook.sshnuke.net/padudpserver.html[cemuhook documentation]

### Patches
Patches are located in the `patches/` directory.

#### `patch-citra-generator-for-cemuhook`

* A patch for the configuration generator of Citra. It adds support for motion and touch configuration in Citra.
* Related pull request: https://github.com/batocera-linux/batocera.linux/pull/8080[#8080]

#### `patch-cemu-generator-for-cemuhook`

* A patch for the configuration generator of Cemu. It adds generation of the cemuhook configuration file `cemuhook.ini` allowing configuration of motion control.
* Written for batocera v35 which contains the Windows build of cemu. This patch will probably not work in batocera v36 and above, because v36 introduces the linux version of cemu.

#### `patch-citra-generator-for-language`

* A patch for the configuration generator of Citra. It fixes broken language detection.
* Related pull request: https://github.com/batocera-linux/batocera.linux/pull/8073[#8073]
* May be applied to batocera v35, will be available in v36.

#### `patch-cemu-generator-for-squashfs`

* A patch for the configuration generator of Cemu. It adds support for arbitrary location of `.rpx` files within Loadiine roms.
* Related pull requests: https://github.com/batocera-linux/batocera.linux/pull/8052[#8052] & https://github.com/batocera-linux/batocera.linux/pull/8053[#8053]
* May be applied to batocera v35, will be available in v36.

#### `patch-batocera-info-for-pro-controller`
* A script that patches `batocera-info` for Switch Pro Controllers.
* For Nintendo controllers, the kernel module https://github.com/emilyst/hid-nx-dkms[hid-nx] is used which provides the battery status as https://github.com/emilyst/hid-nx-dkms/blob/974d6c407296c47390d99f008933846c86f52bb9/hid-nx.c#L1533[level enum] (e.g. `low` and `high`) instead of a percentage.
* This patch has only an effect on the `batocera-info` script and not on the battery level shown in the Emulation Station UI.

### Scripts
Scripts are located in the `bin/` directory.

#### `custom.sh`
* An example for `/userdata/system/custom.sh` that enables all features of this project.

#### `read-temperatures`
* A script to read system temperatures from `hwmon` instead of `thermal_zone`. Useful for hosts where `/sys/devices/virtual/thermal` is not available.

#### `system-summary`
* A script to create a system summary (cpu, memory). May be bound to a key or controller button, e.g.:
+
./userdata/system/configs/multimedia_keys.conf
[source.conf]
----
KEY_F12 1 /userdata/extra/bin/system-summary | sed 's/°/ /' | HOME=/userdata/system XAUTHORITY=/var/lib/.Xauthority DISPLAY=:0.0 osd_cat -f -*-*-bold-*-*-*-38-120-*-*-*-*-*-* -cred -s 3 -d 4
----

#### `on-game-condition`
* A template for files in the `/userdata/system/scripts` directory.

## Emulator configuration for motion and touch control
This section explains the emulator configuration that is required to play games with motion and touch control. This configuration has to be performed once only, it will be persisted across boots.

The configuration generators for Citra and Cemu in batocera v35 don't offer support for motion and touch control. Actually, they even prevent it because they override custom changes in the affected configuration files. To avoid this, the <<Patches>> are required.

Once the configuration is applied, the emulators will behave as follows:

* Touch input is read from the emulator window. This enables the following sources for touch input:
** The touchpad of a DS4 controller
** A smartphone connected via remote touchpad
** A mouse connected to the batocera host

* Motion input is read from a cemuhook server.
** For a Nintendo controller connected to joycond-cemuhook, use `localhost` and `26761`.
** For a DS4 controller connected to ds4drv-cemuhook, use `localhost` and `26762`.
** For a smartphone, use the hostname/ip of the smartphone and the port configured in the _MotionSource_ app.

### Citra
./userdata/system/configs/citra-emu/qt-config.ini
----
[Controls]
profiles\1\touch_device=engine:emu_window
profiles\1\touch_device\default=true
profiles\1\motion_device=engine:cemuhookudp
profiles\1\motion_device\default=false
profiles\1\udp_input_address=localhost
profiles\1\udp_input_address\default=false
profiles\1\udp_input_port=26761
profiles\1\udp_input_port\default=false
----

Notes:

* The settings may be set by either editing the configuration file using a text editor or using the UI: File Manager -> Applications -> citra-emu-config -> Menu _Emulation_ -> Entry _Configure_ -> List Entry _Controls_ -> Tab _Input_ -> Button _Motion / Touch Control..._
* Without patch, the Citra configuration generator will overwrite these settings on game start.

### Cemu
./userdata/system/batocera.conf
----
wiiu.cemuhook_motion_source=DSU1
wiiu.cemuhook_motion_source_is_button_source=1
wiiu.cemuhook_server_ip=127.0.0.1
wiiu.cemuhook_server_port=26761
----

Notes:

* The settings must be set by editing the configuration file using a text editor.
* Without patching the Cemu configuration generator, these settings have no effect.
* Implementation details:
** Without patch, the generator overwrites `/userdata/system/configs/cemu/cemuhook.ini` with `/usr/cemu/cemuhook.ini` on each game start.
** The patch reads the settings from `batocera.conf` and adds them to `/userdata/system/configs/cemu/cemuhook.ini` resulting in
+
./userdata/system/configs/cemu/cemuhook.ini
----
[Input]
motionSource = DSU1
motionSourceIsBtnSource = true
serverIP = localhost
serverPort = 26761
----
