#!/bin/sh
set -eu
. "$(readlink -f "$(dirname "$0")")/.env"

main() {
  package_source="$(find_package_source "${app_name}" "${url}")"
  if [ "${package_source}" ]; then
    "${base_dir}/../extra_patches/mark-dbus-python-as-installed"

    # transitive dependency 'PyGObject_stubs' requires gcc from 2.17
    pip install --root-user-action=ignore 'PyGObject_stubs<2.17' "${package_source}"
  fi
}

main "${@}"
