#!/bin/sh
set -eu

image_tag='v1993/evdevhook2:build'

if ! command -v docker >/dev/null 2>&1; then
  echo >&2 "Docker is required to build evdevhook2."
  false
fi

cat <<'EOF' | docker build -t "${image_tag}" -
FROM debian:bullseye-slim
RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    apt-get install -y --no-install-recommends software-properties-common gpg gpg-agent dirmngr gcc libudev-dev libevdev-dev zlib1g-dev git ca-certificates meson && \
    add-apt-repository 'deb https://ppa.launchpadcontent.net/vala-team/next/ubuntu focal main' && \
    apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4CE987B57DAAC99C && \
    apt-get update && \
    apt-get install -y --no-install-recommends valac libgee-0.8-dev && \
    apt-get clean
WORKDIR /tmp
ENV REPO_URL https://github.com/v1993/evdevhook2.git
CMD name="$(basename "${REPO_URL}" .git)" && \
    target=release &&\
    git clone --recursive --single-branch -c advice.detachedHead=false ${REPO_BRANCH:+--branch "${REPO_BRANCH}"} "${REPO_URL}" "${name}" && \
    cd "${name}" && \
    meson setup --buildtype=release -Db_lto=true "--prefix=${PWD}/${target}/usr" build && \
    meson compile -C build && \
    meson install -C build && \
    find "${target}" -maxdepth 1 -printf "%P\n" | tar -czf "/mnt/${name}-$(git describe --tags)-$(uname -m).tar.gz" -C "${target}" -T -
EOF

docker run --rm -v "${PWD}/releases:/mnt" ${1:+-e "REPO_BRANCH=${1}"} "${image_tag}"
