#!/bin/sh
set -eu
. "$(readlink -f "$(dirname "$0")")/.env"

main() {
  target="${XDG_CACHE_HOME:-/userdata/system/.cache}/${app_name}"
  package="$(provide_package "$(find_url)" "${target}")"
  chmod +x "${package}"
  ln -sf "${package}" "/usr/bin/${app_name}"

  if [ "${port}" ]; then
    printf '[Evdevhook]\nPort=%s\n' "${port}" >"${config_file}"
  fi
}

main "${@}"
