#!/bin/sh
set -eu
. "$(dirname $(readlink -f "$0"))/.env"

main() {
  target="${XDG_CACHE_HOME:-/userdata/system/.cache}/${app_name}"
  package="$(provide_package "${url}" "${target}")"
  chmod +x "${package}"
  ln -sf "${package}" "/usr/bin/${app_name}"

  if [ "${port}" ]; then
    printf '[Evdevhook]\nPort=%s\n' "${port}" >"${config_file}"
  fi
}

main "${@}"
