#!/bin/sh
set -eu
. "$(dirname $(readlink -f "$0"))/.env"

main() {
  package_source="$(find_package_source "${app_name}" "${url}")"
  if [ "${package_source}" ]; then
    /userdata/extra/patches/mark-dbus-python-as-installed

    pip install --root-user-action=ignore "${package_source}"
  fi
}

main "${@}"
