= joycond-cemuhook
:url-joycond-cemuhook: https://github.com/joaorb64/joycond-cemuhook
Motion control for Nintendo controllers

This directory contains files to install and manage {url-joycond-cemuhook}[joycond-cemuhook] which enables motion control for Nintendo controllers. Controllers may be connected via USB or Bluetooth.

== Installation
. Add `install-and-start` to your `/userdata/system/custom.sh`. This will perform the following steps when the host boots:

.. Prepare `pip`, if required.
.. Download the latest version of `joycond-cemuhook` to `download`, if required.
.. Install it.
.. Download and install required dependencies. 
.. Load the kernel module `hid-nx`, if required.
.. Start `joycond-cemuhook` as background daemon.

== Usage
Configure your emulators to listen to `localhost` port `26761`. The https://github.com/joaorb64/joycond-cemuhook/wiki[joycond-cemuhook wiki] has detailed explanations for popular emulators.

NOTE: The default port for the cemuhook protocol is `26760`. The custom port `26761` was chosen to avoid conflicts with other cemuhook servers. It is configurable in the `.env` file.

NOTE: Please pay attention to the patch for Cemu in this project, it is required when you'd like to run the emulator from ES.

== Troubleshooting
* The log file is located at `/userdata/system/logs/joycond-cemuhook.log` (location is configurable in the `.env` file).
* The other scripts (e.g. `is-up`, `stop`) may help to analyse problems, their names should be self-explaining.
