= joycond-cemuhook
:url-joycond-cemuhook: https://github.com/joaorb64/joycond-cemuhook
Motion control for Nintendo controllers

This directory contains files to install and manage {url-joycond-cemuhook}[joycond-cemuhook] which enables motion control for Nintendo controllers. Controllers may be connected via USB or Bluetooth.

== Installation
. Enable this feature as batocera service (Main Menu / System Settings / Services). This will perform the following steps:

.. Prepare `pip`.
.. Download the latest version of `joycond-cemuhook` and its dependencies to a cache directory, if required, and install it.
.. Load the kernel module `hid-nx`.
.. Start `joycond-cemuhook` as background daemon.

== Usage
Configure your emulators to listen to `localhost` port `26761`. The https://github.com/joaorb64/joycond-cemuhook/wiki[joycond-cemuhook wiki] has detailed explanations for popular emulators.

NOTE: The default port for the cemuhook protocol is `26760`. The custom port `26761` was chosen to avoid conflicts with other cemuhook servers. It is configurable in the `.env` file.

NOTE: Please pay attention to the patches for Cemu and Citra in this project, they are required when you'd like to run the emulators from ES.

== Troubleshooting
* The log file is located at `/userdata/system/logs/joycond-cemuhook.log` (location is configurable in the `.env` file).
* The other scripts (e.g. `is-up`, `stop`) may help to analyse problems, their names should be self-explaining.
