#!/bin/sh
set -eu
. "$(dirname $(readlink -f "$0"))/.env"

if pid=$("${base_dir}/is-up"); then
  log "${app_name} is already running with pid ${pid}."
else
  cd "${base_dir}/joycond-cemuhook"
  lsmod | grep -q hid_nx || modprobe hid_nx
  python3 -u joycond-cemuhook.py ${ip:+--ip "${ip}"} ${port:+--port "${port}"} >"${log_file}" 2>&1 &
fi
