#!/bin/sh
set -eu
. "$(dirname $(readlink -f "$0"))/.env"

if pid=$("${base_dir}/is-up"); then
  log "${app_name} is already running with pid ${pid}."
else
  if ! lsmod | grep -q hid_nx; then
    modprobe hid_nx
  fi
  if ! pgrep upowerd >/dev/null; then
    /usr/lib/upowerd 2>&1 | logger &
  fi
  PYTHONUNBUFFERED=true joycond-cemuhook ${ip:+--ip "${ip}"} ${port:+--port "${port}"} >"${log_file}" 2>&1 &
fi
