#!/bin/sh
set -eu

image_tag='kmicki/sdgyrodsu:build'

if ! command -v docker >/dev/null 2>&1; then
  echo >&2 "Docker is required to build SteamDeckGyroDSU."
  false
fi

#
# |     batocera    | buildroot | glibc | archlinux  |      docker
# +-----------------+-----------+-------+------------+------------------
# | 37 (2023/06/18) | 2023.02.1 | 2.36  | 2023-02-05 | 20230205.0.124056
# | 38 (2023/10/14) | 2023.05.1 | 2.37  | 2023-08-03 | 20230725.0.167364
# | 39 (2024/03/07) | 2023.05.1 | 2.37  | 2023-08-03 | 20230725.0.167364
# | 40 (2024/08/11) | 2024.02.1 | 2.38  | 2024-02-04 | 20240204.0.211672
#
cat <<'EOF' | docker build -t "${image_tag}" -
FROM archlinux/archlinux:base-devel-20230725.0.167364
RUN  echo 'Server=https://archive.archlinux.org/repos/2023/08/03/$repo/os/$arch' >/etc/pacman.d/mirrorlist && \
     pacman -Sy --noconfirm git make gcc glibc linux-api-headers ncurses
WORKDIR /tmp
ENV REPO_URL https://github.com/kmicki/SteamDeckGyroDSU.git
CMD name="$(basename "${REPO_URL}" .git)" && \
    target=bin/release &&\
    git clone --recursive --single-branch -c advice.detachedHead=false ${REPO_BRANCH:+--branch "${REPO_BRANCH}"} "${REPO_URL}" "${name}" && \
    cd "${name}" && \
    make && \
    find "${target}" -maxdepth 1 -printf "%P\n" | tar -czf "/mnt/${name}-$(git describe --tags)-$(uname -m).tar.gz" -C "${target}" -T -
EOF

docker run --rm -v "${PWD}/releases:/mnt" ${1:+-e "REPO_BRANCH=${1}"} "${image_tag}"
