#!/bin/sh
set -eu
. "$(readlink -f "$(dirname "$0")")/.env"

main() {
  url="$(find_url)"
  timestamp="$(
    wget -q --spider -S "${url}" 2>&1 \
    | sed -nE 's/\s*Last-Modified: ([^\s].+)/\1/p' \
    | date -u '+%Y-%m-%d.%H-%m' -f -)"
  directory="${app_name}/${timestamp}"

  target="${XDG_CACHE_HOME:-/userdata/system/.cache}/${directory}"
  package="$(provide_package "${url}" "${target}")"

  unzip -j -o "${package}" "SteamDeckGyroDSUSetup/${app_name}" -d /usr/bin/
  chmod +x "/usr/bin/${app_name}"

  "${base_dir}/../bin/install-from-arch" ncurses=? systemd-libs=? hidapi=?=extra
}

main "${@}"
