#!/bin/sh
set -eu
. "$(readlink -f "$(dirname "$0")")/.env"

if "${base_dir}/service" status | grep .; then
  log "${app_name} is already running."
else
  SDGYRO_SERVER_PORT="${port}" "${app_name}" >"${log_file}" 2>&1 &
fi
