= sc-controller
:url-sc-controller: https://github.com/kozec/sc-controller
Motion control for the Steam Controllers

This directory contains files to install and manage {url-sc-controller}[sc-controller] which enables motion and touch control for the Steam Controller.

== Installation
. Add `install-and-start` to your `/userdata/system/custom.sh`. This will perform the following steps when the host boots:

.. Download `sc-controller`, if required.
.. Download and install required dependencies.
.. Start `sc-controller` as background daemon.

== Usage
Configure your emulators to listen to `localhost` port `26768`. The https://github.com/joaorb64/joycond-cemuhook/wiki[joycond-cemuhook wiki] has detailed explanations for popular emulators.

NOTE: The default port for the cemuhook protocol is `26760`. The custom port `26768` was chosen to avoid conflicts with other cemuhook servers. It is configurable in the `.env` file.

NOTE: Please pay attention to the patches for Cemu and Citra in this project, they are required when you'd like to run the emulators from ES.

== Button Mapping
batocera-extra comes with two mapping profiles _Mouse First_ and _Stick First_.

The active button mapping is stored in `profiles/active.sccprofile`. It is set to _Mouse First_ per default.

Mappings can be customized via the sc-controller GUI,
available in the File Manager (Batocera Main Menu / F1 / Applications / sc-controller-config).

=== Mapping Profiles
==== Mouse First
* Analog Stick, Buttons, D-Pad Buttons: XBox 360 Controller
* Left Touchpad: _unused_
* Right Touchpad:
** Mouse incl. Left Click
** With Left Grip pressed: Right Analog Stick incl. Button (without haptic feedback)
* Right Grip: Switch to profile _Stick First_

==== Stick First
* Analog Stick, Buttons, D-Pad Buttons: XBox 360 Controller
* Left Touchpad: _unused_
* Right Touchpad:
** Right Analog Stick incl. Button (without haptic feedback)
** With Left Grip pressed: Mouse incl. Left Click
* Right Grip: Switch to profile _Mouse First_

==== Default Profiles
To add the default profiles of sc-controller to the `profiles` directory,
add the argument `--with-default-profiles` on installation (existing profiles will not be overwritten). Example:
```
./install --with-default-profiles
```

==== Examples
Additional profiles can be found in {url-sc-controller}/tree/master/profile_examples[profile_examples].


== Troubleshooting
* The log file is located at `/userdata/system/logs/sc-controller.log` (location is configurable in the `.env` file).
* The other scripts (e.g. `is-up`, `stop`) may help to analyse problems, their names should be self-explaining.
