#!/bin/sh
set -eu
. "$(readlink -f "$(dirname "$0")")/.env"

main() {
  rm -f "/usr/bin/${app_name}"
  rm -f "/usr/share/applications/${app_name}-config.desktop"
  rm -f "/usr/share/icons/hicolor/512x512/apps/${app_name}.png"
}

main "${@}"
