= linuxmotehook2
Motion control for Nintendo Wiimote controllers

== Configuration
. Create a configuration file with the suffix `.ini` in the `profiles` directory.
** The https://github.com/v1993/linuxmotehook2/wiki[linuxmotehook2 wiki]
has detailed explanations on the configuration file options.
** In the following example, a server is configured on port 26763 that will accept connections from any Wiimote:
+
.profiles/all-wimotes.ini
[source,ini]
----
[Linuxmotehook]
Port=26763
AllowlistMode=false
----
** In the following example, a server is configured on port 26763 for 2 Wiimotes
with the MAC addresses `01:23:45:67:89:AB` and `FE:DC:BA:98:76:54`:
+
.profiles/example.ini
[source,ini]
----
[Linuxmotehook]
Port=26763

[0x0123456789AB]
[0xFEDCBA987654]
----

. To automatically configure Cemu and Citra for a Wiimote motion provider,
  set the port in the `.env` file. Example:
+
.env
[source]
----
port=26763
----

. Enable batocera service _MOTION_WIIMOTE_

=== Profiles
linuxmotehook2 manages Wiimote extensions, e.g. Nunchucks and Classic Controllers, as separate devices.
The cemuhook https://v1993.github.io/cemuhook-protocol/[protocol] has a limit of four devices per server.
To cope with this limitation, use one profile per Wiimote, each running on a separate server with a dedicated port.
The emulators must be configured accordingly. Example:

.profiles/white.ini
[source,ini]
----
[Linuxmotehook]
Port=26763

[0x0123456789AB]
----

.profiles/gold.ini
[source,ini]
----
[Linuxmotehook]
Port=26764

[0xFEDCBA987654]
----

In this example, we have configured one server for a white Wiimote served on port 26763 and another one for a golden Wiimote served on port 26764.
