#!/bin/sh
set -u
echo "$(date -Iseconds)" "${0}" "${@}" >&2

apply_patches() {
  /userdata/extra/patches/relocate-root-dotfiles-to-home
  /userdata/extra/patches/patch-joycond-for-flatpak
  /userdata/extra/patches/patch-cemu-generator-for-cemuhook
  /userdata/extra/patches/mark-dbus-python-as-installed
}

case "${1-}" in
  enable)  ;;
  disable) ;;
  start)   apply_patches
           ;;
  stop)    ;;
  *)
esac
