#!/bin/sh
set -eu
. "$(readlink -f "$(dirname "$0")")/.env"

if "${base_dir}/service" status | grep .; then
  log "${app_name} is already running."
else
  "${base_dir}/../bin/upowerd-start"
  "${app_name}" ${config_file:+"${config_file}"} >"${log_file}" 2>&1 &
fi
