#!/bin/sh
set -eu
. "$(readlink -f "$(dirname "$0")")/.env"

if pid=$("${base_dir}/is-up"); then
  log "${app_name} is already running with pid ${pid}."
else
  SDGYRO_SERVER_PORT="${port}" "${app_name}" >"${log_file}" 2>&1 &
fi
