#!/bin/sh
set -eu
. "$(dirname $(readlink -f "$0"))/.env"
. "${base_dir}/profile-support.sh"

if [ "${#}" -eq 0 ]; then
  pgrep -f "/tmp/.*/usr/bin/${app_name}"
else
  for profile in "${@}"; do
    path=$(path_of "${profile}") || return 2
    pgrep -f "/tmp/.*/usr/bin/${app_name} ${path}"
  done
fi
