= linuxmotehook2
:url-linuxmotehook2: https://github.com/v1993/linuxmotehook2
Motion control for Nintendo Wiimote controllers

This directory contains files to install and manage {url-linuxmotehook2}[linuxmotehook2] which enables motion control for Nintendo Wiimotes.

== Installation
. Add `install-and-start` to your `/userdata/system/custom.sh`. This will perform the following steps when the host boots:

.. Install `linuxmotehook2` from the `releases` directory.
.. Download and install required dependencies.
.. Start `linuxmotehook2` as background daemon.

== Usage
. Create a configuration file with the suffix `.ini` in the `profiles` directory. Example:
+
.profiles/example.ini
[source,ini]
----
[Linuxmotehook]
Port=26763
SendButtons=true

[0x0123456789AB]
[0xFEDCBA987654]
----
+
In this example, a server is configured on port 26763 for 2 Wiimotes with the MAC addresses `01:23:45:67:89:AB` and `FE:DC:BA:98:76:54`. The https://github.com/v1993/linuxmotehook2/wiki[linuxmotehook2 wiki] has detailed explanations on the configuration file options.

. Configure your emulators to listen to `localhost` and the port configured in one of your configuration files.

[NOTE]
====
- The server will only manage a Wiimote if its MAC address is listed in the configuration file.
- Please pay attention to the patches for Citra and Cemu in this project, they are required when you'd like to run the emulators from ES.
====

=== Profiles
linuxmotehook2 manages Wiimote extensions, e.g. a Nunchuck or WiimotePlus sensor, as separate devices. The cemuhook https://v1993.github.io/cemuhook-protocol/[protocol] has a limit of four devices per server. To cope with this limitation, use one profile per Wiimote, each running on a separate server with a dedicated port. The emulators must be configured accordingly. Example:

.profiles/white.ini
[source,ini]
----
[Linuxmotehook]
Port=26763
SendButtons=true
[0x0123456789AB]
----

.profiles/gold.ini
[source,ini]
----
[Linuxmotehook]
Port=26764
SendButtons=true
[0xFEDCBA987654]
----

In this example, we have configured one server for a white Wiimote served on port 26763 and another one for a golden Wiimote served on port 26764.

== Troubleshooting
* The log files are located at `/userdata/system/logs/` using the filename pattern `linuxmotehook2-${PROFILE_NAME}.log` (location is configurable in the `.env` file).
* The other scripts (e.g. `is-up`, `stop`) may help to analyse problems, their names should be self-explaining.

== Implementation details
batocera does not contain any tools to build linuxmotehook2 and its dependencies. Thus, the binaries are provided in subdirectory `releases`, and the dependencies are downloaded as binary packages from the Arch Linux package repository.

=== Build
linuxmotehook2 currently does not provide any binary releases. If you're not happy with the pre-built binaries distributed within this project, you can use the `build` script to simplify the build. The script is self-contained, its only requirement is a host with Docker installed.

==== Specify the release
When run without any arguments, the build script uses the latest commit of the default branch of the linuxmotehook2 Github repository. To use a specific tag or branch, you can handle its name as argument, e.g.

[source,console]
----
$ ./build v0.1.4
----

==== Integration in batocera
To use a custom release within batocera, put the release archive into the `releases` subdirectory and change the `package` variable in the `.env` file. Example:

..env
[source,env]
----
package="linuxmotehook2-v0.1.4-$(uname -m).tar.gz"
----

==== Build details
The build script will perform the following steps:

. Prepare a Docker container that is compatible with the current version of batocera (glibc version) and the architecture of the host system.
. Download all required dependencies.
. Run the build.
. Package all files to a tar archive in the `releases` subdirectory of the current working directory.
