#!/bin/sh
. "$(dirname $(readlink -f "$0"))/.env"

if ! "${base_dir}/is-up"; then
  "${base_dir}/start"
  sleep 1
fi

LANG=C DISPLAY=:0 xterm -en C.UTF-8 -e "$(dirname $0)/show-url; sleep \"${timeout}\""
