#!/bin/sh
set -eu
. "$(readlink -f "$(dirname "$0")")/.env"

main() {
  package_source="$(find_package_source "${package_name}" "${url}")"
  if [ "${package_source}" ]; then
    "${base_dir}/../patches/mark-dbus-python-as-installed"

    pip install --root-user-action=ignore --use-pep517 "${package_source}"
    ln -s "${package_name}" "/usr/bin/${app_name}"
  fi
}

main "${@}"
