#!/bin/sh
set -eu
. "$(readlink -f "$(dirname "$0")")/.env"

if pid=$("${base_dir}/is-up"); then
  log "${app_name} is already running with pid ${pid}."
else
  PATH="${base_dir}/quirk:$PATH" "${app_name}" --udp ${host:+--udp-host "${host}"} ${port:+--udp-port "${port}"} >"${log_file}" 2>&1 &
fi
