#!/bin/sh
set -eu
file='/etc/udev/rules.d/99-sony-controllers.rules'

main() {
  if [ -e "${file}" ]; then
    echo >&2 "Error: '${file}' exists."
    return 1
  fi

  cat >"${file}" <<EOF
KERNEL=="hidraw*", SUBSYSTEM=="hidraw", ATTRS{idVendor}=="054c", ATTRS{idProduct}=="05c4", GROUP="input", MODE="0660"
KERNEL=="hidraw*", SUBSYSTEM=="hidraw", KERNELS=="0005:054C:05C4.*", GROUP="input", MODE="0660"
KERNEL=="hidraw*", SUBSYSTEM=="hidraw", ATTRS{idVendor}=="054c", ATTRS{idProduct}=="0ce6", GROUP="input", MODE="0660"
KERNEL=="hidraw*", SUBSYSTEM=="hidraw", KERNELS=="0005:054C:0CE6.*", GROUP="input", MODE="0660"
EOF
}

main "${@}"
