#!/bin/sh
set -eu
. "$(readlink -f "$(dirname "$0")")/.env"

if "${base_dir}/service" status | grep .; then
  log "${app_name} is already running."
else
  # AppImage requires FUSE, missing for v39 on aarch64
  "${base_dir}/../bin/fuse-start"

  [ -z "${ip-}" ] || export SCC_SERVER_IP="${ip}"
  [ -z "${port-}" ] || export SCC_SERVER_PORT="${port}"
  "${app_name}" daemon --alone "${profile}" debug >"${log_file}" 2>&1 &
  sleep 2
fi
