#!/bin/sh
set -eu
. "$(readlink -f "$(dirname "$0")")/.env"

if "${base_dir}/service" status | grep .; then
  log "${app_name} is already running."
else
  PATH="${PATH}:${base_dir}/quirk" sc-controller daemon --alone "${profile}" debug >>"${log_file}" 2>&1 &
fi
